### ISSUE TITLE
Zookeeper Connection issue

### ISSUE THREAD

**Issue by bismark64** [enigmo/rsolr-cloud#5]
Hi guys, I'm trying to connect with SolrCloud using this gem and I'm getting blocked with a small issue:

``` ruby
zk = ZK.new('host:2181')
=> #<ZK::Client::Threaded:70262340244680 zk_session_id=0x15361a49d870039 ...> 
cloud_connection = RSolr::Cloud::Connection.new(zk)
=> ZK::Exceptions::NoNode: inputs: {:path=>"/live_nodes", :watcher=>#<Zookeeper::Callbacks::WatcherCallback:0x007fce6ed042f8 @completed=false, @proc=#<Proc:0x007fce6ed04078@/Users/bismark/.rvm/gems/ruby-2.2.0@tugg-server/gems/zookeeper-1.4.11/lib/zookeeper/callbacks.rb:24>>}
```

Then I tried also this way:

``` ruby
zk = ZK.new('host:2181/solr')
=> #<ZK::Client::Threaded:70262340244680 zk_session_id=0x15361a49d870039 ...> 
cloud_connection = RSolr::Cloud::Connection.new(zk)
=> ZK::Exceptions::NoNode: inputs: {:path=>"/collections/storefront/state.json", :watcher=>#<Zookeeper::Callbacks::WatcherCallback:0x007f926727b360 @completed=false, @proc=#<Proc:0x007f926727b270@/Users/bismark/.rvm/gems/ruby-2.2.0@tugg-server/gems/zookeeper-1.4.11/lib/zookeeper/callbacks.rb:24>>}
```

Apparently there is something wrong in my Solr configuration, but honestly this is the first time I use SolrCloud so I can't figure out what's wrong..

![screen shot 2016-03-15 at 14 47 20](https://cloud.githubusercontent.com/assets/3027525/13788121/652ddd46-eabd-11e5-9d7c-0d1e1e335a70.png)

Any help would be very welcome! Thanks

**Comment by kmrshntr** [comment]
That seems to be a problem about connection to zookeeper.
What value did you specify in -z (or -zkHost) option when you started SolrCloud? You can confirm it on the dashboard of SolrCloud.
Please fill the parameter of `ZK.new` with exactly same value as that's option.
